#' heatmaps
#'
#' @param Dshort data.frame generated by agg.sleepsight
#' @param Dlong data.frame generated by agg.sleepsight
#' @param heatmapsfile png.file to which the plot should be written to
#' @param heatmapsfile_steps png.file to which the plot should be written to
#' @param simplify.behavioralclasses TRUE or FALSE
#' @return no output, just a file is stored
#' @export
#' @importFrom graphics plot
#' @importFrom utils timestamp
#' @import ggplot2
# #' @importFrom ggplot2  aes element_text geom_raster geom_tile ggplot labs scale_colour_manual scale_fill_continuous scale_fill_manual scale_x_discrete theme theme_bw xlab ylab
heatmaps = function(Dshort, Dlong, heatmapsfile, heatmapsfile_steps, simplify.behavioralclasses) {
  cat("\n* plot heatmaps")
  # Declare functions:
  addDoublePlot = function(x) {
    doubleplot = x
    doubleplot$hour_in_day = doubleplot$hour_in_day + 24
    doubleplot$date = doubleplot$date - 1
    x = rbind(x, doubleplot)
    x = x[order(x$hour_in_day,x$date),]
    x$date = as.character(x$date)
    return(x)
  }
  #-------------------------------------------
  # color coding:
  coldic <- c("active" = "#D55E00",
              "inactive" = "#F0E442",
              "sleep" = "#56B4E9",
              "sustained inactive" = "#009E73",
              "inconsluvie" = "#CC79A7",
              "no data" = "#999999")
  if (simplify.behavioralclasses == TRUE) {
    # simplify status classes to only active and inactive:
    Dshort$status[which(Dshort$status %in% c("sustained inactive","sleep") == TRUE)] = "inactive"
  }
  dates_on_x_axis = unique(Dshort$date)
  dates_on_x_axis = dates_on_x_axis[seq(1,length(dates_on_x_axis),15)]
  Dshort$date = as.Date(Dshort$date)
  Dshort = addDoublePlot(Dshort)
  png(filename = heatmapsfile ,width = 15, height = 7,units = "in",res = 400)
  myplot = ggplot(Dshort) +
    geom_tile(
      aes(date, Dshort$hour_in_day, fill=Dshort$status)) + #, color=Dshort$status
    xlab("") +
    ylab("Hour in day") +
    theme_bw() +
    labs(fill = "status") +
    scale_colour_manual(values = coldic) +
    scale_fill_manual(values = coldic) +
    scale_x_discrete(breaks = dates_on_x_axis) +
    theme(axis.text.x = element_text(angle = 45))
  print(myplot)
  dev.off()
  
  # Heatmap of steps
  dates_on_x_axis = unique(Dlong$date)
  dates_on_x_axis = dates_on_x_axis[seq(1,length(dates_on_x_axis),15)]
  Dlong$date = as.Date(Dlong$date)
  Dlong = addDoublePlot(Dlong)
  Dlong$steps = as.numeric(Dlong$steps)
  png(filename = heatmapsfile_steps ,width = 15, height = 7,units = "in",res = 400)
  myplot = ggplot(Dlong, aes(date, Dlong$hour_in_day)) +
    geom_raster(aes(fill=Dlong$steps)) +
    xlab("") +
    ylab("Hour in day") +
    theme_bw() +
    labs(fill = "steps per 30 minutes") +
    scale_fill_continuous(low="black", high="green",na.value = "#000000") + 
    scale_x_discrete(breaks = dates_on_x_axis) +
    theme(axis.text.x = element_text(angle = 45))
  print(myplot)
  dev.off()
}